chore: bump react-redux to v7
sigfox/redux-router pull request #1
Opened 2021-07-07 15:21 UTC by laetitiadufau

2021-07-07 15:21 UTC, laetitiadufau commented
BREAKING CHANGES

2021-07-09 14:06 UTC, lbdremy approved these changes

2021-07-09 14:10 UTC, lbdremy commented on src/ReduxRouter.js
>      super(props, context);
context is legacy

2021-07-09 14:16 UTC, lbdremy commented on src/ReduxRouter.js
> +  return function WrappedComponent(props) {
it is important to have a proper displayName to display correctly in react dev tools

e.g:

```
function withSubscription(WrappedComponent) {
  class WithSubscription extends React.Component {/* ... */}
  WithSubscription.displayName = `WithSubscription(${getDisplayName(WrappedComponent)})`;
  return WithSubscription;
}

function getDisplayName(WrappedComponent) {
  return WrappedComponent.displayName || WrappedComponent.name || 'Component';
}
```

2021-07-09 14:21 UTC, lbdremy requested changes
See comments

2021-07-09 16:47 UTC, lbdremy approved these changes

2021-07-12 08:50 UTC, merged